config/routes.rb
Rails.application.routes.draw do
  resources :goods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good.rb
class Good < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
    def index
      @goods = Good.all
    end

    def show
      @good = Good.find(params[:id])
    end

    def new
      @good = Good.new
    end

    def create
      @good = Good.new(good_params)
      if @good.save
        redirect_to goods_path
      else
        render :new
      end
    end

    def destroy
      @good = Good.find(params[:id])
      @good.destroy
      redirect_to goods_path
    end

    def edit
      @good = Good.find(params[:id])
    end

    def update
      @good = Good.find(params[:id])
        if @good.update(good_params)
          redirect_to goods_path
        else
          render :edit
        end
    end

    private
      def good_params
        params.require(:good).permit(:brand, :category, :price)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/edit.html.erb
<%= form_for @good do |f| %>
<div>
  <%= f.label :brand %>
  <%= f.text_field :brand %>
</div>
<div>
  <%= f.label :category %>
  <%= f.text_area :category %>
</div>
<div>
  <%= f.label :price %>
  <%= f.number_field :price %>
</div>
<div>
  <%= f.submit %>

</div>
<% end %>

app/views/goods/index.html.erb
<h1>Inventory</h1>
<%= link_to "Add", new_good_path %>
<table>
  <thead>
    <th>Brand</th>
    <th>Category</th>
    <th>Price</th>
  </thead>
  <% @goods.each do | good | %>
  <tr>
     <td><%= good.brand %></td>
     <td><%= good.category %></td>
     <td><%= good.price %></td>
     <td>

       <%= link_to "Edit", edit_good_path(good) %>
       <%= link_to "Delete", good, method: :delete, data: {confirm: "Do you really want to delete this good?"} %>
     </td>
  </tr>
  <% end %>
</table>

app/views/goods/new.html.erb
<%= form_for @good do |f| %>
<div>
  <%= f.label :brand %>
  <%= f.text_field :brand %>
</div>
<div>
  <%= f.label :category %>
  <%= f.text_area :category %>
</div>
<div>
  <%= f.label :price %>
  <%= f.number_field :price %>
</div>
<div>
  <%= f.submit %>

</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>